<a href="https://colab.research.google.com/github/AnkitShaw-100/Python-Basics/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
x = [1,2,3,4]
y = np.array([1,2,3,4,5])
print(y)
print(type(y))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
l = []

for i in range(1,5):
  t = int(input("Enter : "))
  l.append(t)

  print(np.array(l))

Enter : 1
[1]
Enter : 2
[1 2]
Enter : 3
[1 2 3]
Enter : 4
[1 2 3 4]


In [ ]:
arr2 = np.array([[1,2,3,4],[1,2,3,4]])
print(arr2)
print("Dimension : ",arr2.ndim)


[[1 2 3 4]
 [1 2 3 4]]
Dimension :  2


In [ ]:
arr3 = np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
print(arr3)
print("Dimension : ",arr3.ndim)

[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]
Dimension :  3


In [ ]:
arr_zero = np.zeros(4)
arr_zero1 = np.zeros((2,5))
print(arr_zero)
print(arr_zero1)

[0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
arr_ones = np.ones(4)
arr_ones1 = np.ones((2,5))
print(arr_ones)
print(arr_ones1)

[1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
arr_empty = np.empty(4)
arr_empty1 = np.empty((2,5))
print(arr_empty)
print(arr_empty1)

[1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
arr_range = np.arange(4)
print(arr_range)

[0 1 2 3]


In [ ]:
arr_dia = np.eye(4)
print(arr_dia)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
arr_lin = np.linspace(0, 10, num=5)
print(arr_lin)

[ 0.   2.5  5.   7.5 10. ]


In [ ]:
var = np.random.rand(4)
var_1 = np.random.rand(2,5)
print("1D : ",var)
print("2D : ",var_1)

1D :  [0.25914113 0.03368927 0.64533946 0.958626  ]
2D :  [[0.62708936 0.494884   0.21395024 0.74972608 0.66999978]
 [0.52781976 0.22271237 0.44882607 0.88958559 0.27173286]]


In [ ]:
var2 = np.random.randn(4)
var_2 = np.random.randn(2,5)
print("1D : ",var2)
print("2D : ",var_2)

1D :  [ 1.29286952 -1.22927814  0.58739613  2.65520162]
2D :  [[ 1.1031761   0.08319079  0.37218864  0.34549703  1.39090097]
 [-0.80467772  0.24388445 -0.78117598 -0.90182347 -1.31407146]]


In [ ]:
ranf = np.random.randint(1,10,5)
print(ranf)


[3 4 6 2 5]


In [ ]:
var = np.array([1,2,3,4])
print("Datatype : ", var.dtype)

Datatype :  int64


In [ ]:
a = [1,2,3,4,5]
b = [10,11,12,13,14]

sum = np.array(a) + np.array(b)
print("Additon :",sum)

sub = np.array(a) - np.array(b)
print("Subtraction :",sub)

mul = np.array(a) * np.array(b)
print("Multiplication :",mul)

div = np.array(a) / np.array(b)
print("Division :",div)

mod = np.array(a) % np.array(b)
print("Modulus :",mod)

exp = np.array(a) ** np.array(b)
print("Exponent :",exp)

log = np.log(np.array(a))
print("Logarithm :",log)

Additon : [11 13 15 17 19]
Subtraction : [-9 -9 -9 -9 -9]
Multiplication : [10 22 36 52 70]
Division : [0.1        0.18181818 0.25       0.30769231 0.35714286]
Modulus : [1 2 3 4 5]
Exponent : [         1       2048     531441   67108864 6103515625]
Logarithm : [0.         0.69314718 1.09861229 1.38629436 1.60943791]
